using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DeadworksManaged.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class GameEventSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var gameEventFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".gameevents", StringComparison.OrdinalIgnoreCase));

        var parsed = gameEventFiles
            .Select(static (file, ct) =>
            {
                var text = file.GetText(ct)?.ToString() ?? "";
                var fileName = System.IO.Path.GetFileName(file.Path);
                return (fileName, events: GameEventParser.Parse(text));
            })
            .Collect();

        context.RegisterSourceOutput(parsed, static (spc, allFiles) =>
        {
            // Sort by filename so core.gameevents (c) is processed before game.gameevents (g).
            // Last-seen wins, so game.gameevents overrides core.gameevents for duplicate events.
            var sorted = allFiles.OrderBy(f => f.fileName, StringComparer.OrdinalIgnoreCase).ToList();

            var eventMap = new Dictionary<string, GameEventDefinition>();
            foreach (var (_, fileEvents) in sorted)
            {
                foreach (var evt in fileEvents)
                {
                    eventMap[evt.Name] = evt;
                }
            }

            var events = eventMap.Values.ToList();
            events.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.Ordinal));

            var classesSource = GenerateEventClasses(events);
            spc.AddSource("GameEvents.g.cs", SourceText.From(classesSource, Encoding.UTF8));

            var factorySource = GenerateFactory(events);
            spc.AddSource("GameEventFactory.g.cs", SourceText.From(factorySource, Encoding.UTF8));
        });
    }

    private static string GenerateEventClasses(List<GameEventDefinition> events)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine();
        sb.AppendLine("namespace DeadworksManaged.Api;");
        sb.AppendLine();

        foreach (var evt in events)
        {
            if (evt.Fields.Count == 0)
                continue;

            var className = ToPascalCase(evt.Name) + "Event";
            sb.AppendLine($"[GeneratedCode(\"DeadworksManaged.Generators\", \"1.0\")]");
            sb.AppendLine($"public sealed class {className} : GameEvent");
            sb.AppendLine("{");
            sb.AppendLine($"    internal {className}(nint handle) : base(handle) {{ }}");

            foreach (var field in evt.Fields)
            {
                EmitProperty(sb, field.Name, field.Type);
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static readonly HashSet<string> BasePropertyNames = new HashSet<string> { "Name", "Handle" };

    private static void EmitProperty(StringBuilder sb, string fieldName, string fieldType)
    {
        var propName = ToPascalCase(fieldName);
        var newModifier = BasePropertyNames.Contains(propName) ? "new " : "";

        switch (fieldType)
        {
            case "string":
                sb.AppendLine($"    public {newModifier}string {propName} => GetString(\"{fieldName}\");");
                break;

            case "bool":
                sb.AppendLine($"    public {newModifier}bool {propName} => GetBool(\"{fieldName}\");");
                break;

            case "byte":
            case "short":
            case "long":
            case "int":
                sb.AppendLine($"    public {newModifier}int {propName} => GetInt(\"{fieldName}\");");
                break;

            case "float":
                sb.AppendLine($"    public {newModifier}float {propName} => GetFloat(\"{fieldName}\");");
                break;

            case "uint64":
                sb.AppendLine($"    public {newModifier}ulong {propName} => GetUint64(\"{fieldName}\");");
                break;

            case "player_controller":
                sb.AppendLine($"    public {newModifier}CBasePlayerController? {propName} => GetPlayerController(\"{fieldName}\");");
                break;

            case "player_pawn":
                sb.AppendLine($"    public {newModifier}CBasePlayerPawn? {propName} => GetPlayerPawn(\"{fieldName}\");");
                break;

            case "player_controller_and_pawn":
            {
                var newCtrl = BasePropertyNames.Contains(propName + "Controller") ? "new " : "";
                var newPawn = BasePropertyNames.Contains(propName + "Pawn") ? "new " : "";
                sb.AppendLine($"    public {newCtrl}CBasePlayerController? {propName}Controller => GetPlayerController(\"{fieldName}\");");
                sb.AppendLine($"    public {newPawn}CBasePlayerPawn? {propName}Pawn => GetPlayerPawn(\"{fieldName}\");");
                break;
            }

            case "ehandle":
                sb.AppendLine($"    public {newModifier}CBaseEntity? {propName} => GetEHandle(\"{fieldName}\");");
                break;
        }
    }

    private static string GenerateFactory(List<GameEventDefinition> events)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine();
        sb.AppendLine("namespace DeadworksManaged.Api;");
        sb.AppendLine();
        sb.AppendLine("[GeneratedCode(\"DeadworksManaged.Generators\", \"1.0\")]");
        sb.AppendLine("public static partial class GameEventFactory");
        sb.AppendLine("{");
        sb.AppendLine("    public static GameEvent Create(string name, nint handle)");
        sb.AppendLine("    {");
        sb.AppendLine("        GameEvent e = name switch");
        sb.AppendLine("        {");

        foreach (var evt in events)
        {
            if (evt.Fields.Count == 0)
                continue;

            var className = ToPascalCase(evt.Name) + "Event";
            sb.AppendLine($"            \"{evt.Name}\" => new {className}(handle),");
        }

        sb.AppendLine("            _ => new GameEvent(handle),");
        sb.AppendLine("        };");
        sb.AppendLine("        e.Name = name;");
        sb.AppendLine("        return e;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ToPascalCase(string snakeCase)
    {
        var sb = new StringBuilder();
        bool capitalizeNext = true;
        foreach (char c in snakeCase)
        {
            if (c == '_')
            {
                capitalizeNext = true;
                continue;
            }

            if (capitalizeNext)
            {
                sb.Append(char.ToUpperInvariant(c));
                capitalizeNext = false;
            }
            else
            {
                sb.Append(c);
            }
        }
        return sb.ToString();
    }
}
